### ISSUE TITLE
Changing controller name breaks default translations

### ISSUE THREAD

**Issue by tigris** [plataformatec/devise#2102]
If you change the paths for a devise controller, such is common for renaming the registrations controller to users via `controllers: { registrations: 'users' }` in your `config/routes.rb` file, then the translation keys in the default yaml file are now wrong.

I'm not entirely sure it's a bug, but it would be nice if I didn't have to completely duplicate the entire "registrations" section from the default devise yaml, and call it "users" instead, when the content is identical and I just prefer my path to be /users/edit instead of /registrations/edit. I guess this is due to the `set_flash_message` method using `controller_name` to figure out the key, whereas other things like route helpers use the original controller name, e.g. `edit_user_registrations_path`.

Also, the missing translation error I get is `en.devise.users.user.updated`, but the devise key is actually `en.devise.registrations.updated`. Note the lack of extra .user on that, which is the resource_name in set_flash_message, so I'm not entirely sure it's correct from the outset.

**Comment by steakchaser** [comment]
Good call on just re-using the existing translations via yaml syntax.  This worked for me:

devise.en.yml
````yaml
en:
  devise:
    sessions: &sessions
      signed_in: 'Signed in successfully.'
      signed_out: 'Signed out successfully.'
    user_sessions: *sessions
````
