### ISSUE TITLE
I18n::InvalidPluralizationData in Registrations#new

### ISSUE THREAD

**Issue by ulugbekov** [plataformatec/devise#2120]
translation data {:one=>"is too short (minimum is 1 character)", :other=>"is too short (minimum is %{count} characters)"} can not be used with :count => 6

I am using russian and english locales. If I add client_side_validations validate: true option to devise's form this exception is being raised.  Russian locale uses, one, other, many, few.

Is there any way to solve this bug.

**Comment by KlavaKurochkina** [comment]
I have same error. What is the answer?

**Comment by sunloverz** [comment]
The same error

**Comment by tegon** [comment]
@sunloverz Thank you for your report.

Could you please open another issue with more information?
> Like for example: 
> * Rails version
> * Devise version
> * Steps to reproduce the error

Will be even more helpful if you provide a sample application or a test case that reproduces the error.

Thanks!

**Comment by sunloverz** [comment]
Added this locales to devise.ru.yml and it works like a charm )

```
  errors:
    messages:
      already_confirmed: "уже подтверждена. Пожалуйста, попробуйте войти в систему"
      confirmation_period_expired: "должен быть подтвержден в течении %{period}, пожалуйста, запросите подтверждение аккаунта завтра"
      expired: "устарела. Пожалуйста, запросите новую"
      not_found: "не найдена"
      not_locked: "не заблокирована"
      not_saved:
        one: "%{resource}: сохранение не удалось из-за %{count} ошибки"
        few: "%{resource}: сохранение не удалось из-за %{count} ошибок"
        many: "%{resource}: сохранение не удалось из-за %{count} ошибок"
        other: "%{resource}: сохранение не удалось из-за %{count} ошибки"
```
