### ISSUE TITLE
Calling user_signed_in? in test when user is not confirmed causes redirect

### ISSUE THREAD

**Issue by mszyndel** [plataformatec/devise#2609]
Let's say I have
- a user created by fixtures which is unconfirmed and therefore unable to sign in
- a test in which I sign in this user using `sign_in` helper
- this tests requests an action which calls either `current_user` or `user_signed_in?`
- action doesn't have `authenticate_user!` filter

as a result I am being redirected to `new_session` path for user.

Is this expected behavior? Especially when it comes to `user_signed_in?`?

I am running
Rails 4.0.0
Devise from github master branch
All tests are in test/unit

Example code

```
require 'test_helper'

class StaticsControllerTest < ActionController::TestCase

  setup do
    @request.env["devise.mapping"] = Devise.mappings[:user]
  end

  test "get test" do
    sign_in users(:unconfirmed_user)
    get :test
    assert_template 'test'
  end
end
```

```
unconfirmed_user:
  email: john.doe@example.com
  company: example
  confirmation_token: e449873f4be59e4d7846a0f32c5252c5425fa30102e9c8f5f65b5f4ae6bc3f66
```

```
class StaticsController < ApplicationController
  def test
    user_signed_in?
  end
end
```

```
  1) Failure:
StaticsControllerTest#test_get_test [<edited>/test/functional/statics_controller_test.rb:12]:
expecting <"test"> but rendering with <[]>
```
