### ISSUE TITLE
Cannot test reset password using Capybara, token is not passed into custom mailer

### ISSUE THREAD

**Issue by TrevorHinesley** [plataformatec/devise#2910]
I'm using Rails 4.1.0.rc1 with Devise 3.2.3. The reset password functionality works in reality, but I cannot get the test to pass because as soon as the "Reset password" button is clicked using Capybara, my custom mailer breaks because the token is not passed into the mailer:

```
require 'spec_helper'

describe "Password" do

  describe "#new" do
    let(:user) { create(:user) }

    it "emails user when a password reset is requested" do
      visit sign_in_path
      click_link "click here"
      fill_in "Email", :with => user.email
      click_button "Reset password"
      current_path.should eq(unauthenticated_root_path)
      last_email.to.should include(user.email)
    end
  end
end
```

And the resulting error is:

```
Failures:

  1) Password #new emails user when a password reset is requested
  Failure/Error: click_button "Reset password"
  NoMethodError:
  undefined method `[]' for nil:NilClass
  # ./app/mailers/my_devise_mailer.rb:12:in `reset_password_instructions'
  # ./spec/features/devise/password_spec.rb:12:in `block (3 levels) in <top (required)>'
  # -e:1:in `<main>'
```
