### ISSUE TITLE
Cannot test reset password using Capybara, token is not passed into custom mailer

### ISSUE THREAD

**Issue by TrevorHinesley** [plataformatec/devise#2914]
I'm using Rails 4.1.0.rc1 with Devise 3.2.3. The reset password functionality works in reality, but I cannot get the test to pass because as soon as the "Reset password" button is clicked using Capybara, my custom mailer breaks because the token is not passed into the mailer:

``` ruby
require 'spec_helper'

describe "Password" do

  describe "#new" do
    let(:user) { create(:user) }

    it "emails user when a password reset is requested" do
      visit sign_in_path
      click_link "click here"
      fill_in "Email", :with => user.email
      click_button "Reset password"
      current_path.should eq(unauthenticated_root_path)
      last_email.to.should include(user.email)
    end
  end
end
```

And the resulting error is:

```
Failures:

  1) Password #new emails user when a password reset is requested
  Failure/Error: click_button "Reset password"
  NoMethodError:
  undefined method `[]' for nil:NilClass
  # ./app/mailers/my_devise_mailer.rb:12:in `reset_password_instructions'
  # ./spec/features/devise/password_spec.rb:12:in `block (3 levels) in <top (required)>'
  # -e:1:in `<main>'
```

Below is the custom mailer, all you have to do is run the above test with the below mailer:

``` ruby
class MyDeviseMailer < MandrillMailer::TemplateMailer
  include Devise::Controllers::UrlHelpers

  default from: "blah@blah.com"

  def reset_password_instructions(user, token, hsh = {})
    mandrill_mail template: 'Reset Password',
                  subject: 'Reset your password',
                  to: user.email,
                  vars: {
                    'FIRST_NAME' => user.try(:first_name).try(:capitalize),
                    'RESET_PASSWORD_URL' => edit_user_password_url(reset_password_token: token)
                  }
  end
end
```

And here is the password/new view:

``` erb
<div class="container">
  <div class="row">

    <div class="row">
      <div class="login-box">
        <h2>Forgot your password?</h2>

        <%= form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :post, class: "form-horizontal" }) do |f| %>
          <%= devise_error_messages! %>

          <fieldset>
            <%= f.email_field :email, class: "input-large col-xs-12", placeholder: "Email", :autofocus => true %>

            <div class="clearfix"></div>
            <div class="field-spacer"></div>

            <%= f.submit "Reset password", class: "btn btn-primary col-xs-12" %>

            <div class="clearfix"></div>
            <div class="field-spacer"></div>

          </fieldset>
        <% end %>
      </div>
    </div><!--/row-->

      </div><!--/row-->   

</div><!--/container-->
```
