### ISSUE TITLE
Devise 3.4 failing RSpec tests

### ISSUE THREAD

**Issue by DanielKehoe** [plataformatec/devise#3243]
My example application [rails-devise](https://github.com/RailsApps/rails-devise) contains a few simple feature tests for Devise sign in:

```
feature 'Sign in', :devise do

  scenario 'user cannot sign in if not registered' do
    signin('test@example.com', 'please123')
    expect(page).to have_content I18n.t 'devise.failure.not_found_in_database'
  end

end
```

The test works fine with earlier versions of Devise, where the _config/locales/devise.en.yml_ file contains:

```
en:
  devise:
    failure:
      not_found_in_database: "Invalid email address or password."
```

With the release of Devise 3.4, the _config/locales/devise.en.yml_ file is changed:

```
en:
  devise:
    failure:
      not_found_in_database: "Invalid %{authentication_keys} or password."
```

Now RSpec shows a failure:

```
Failures:

  1) Sign in user cannot sign in if not registered
     Failure/Error: expect(page).to have_content I18n.t "devise.failure.not_found_in_database"
       expected to find text "Invalid %{authentication_keys} or password." in "Toggle navigation Home Sign in Sign up × Invalid email or password. Sign in Sign up Email Forgot password? Password Remember me"
     # ./spec/features/users/sign_in_spec.rb:13:in `block (2 levels) in <top (required)>'
```

It seems when the tests run, the interpolation of `Invalid %{authentication_keys} or password.` doesn't happen.

How can I fix my RSpec tests to accommodate Devise 3.4?
