### ISSUE TITLE
Persistent schema issue(?) after upgrading to version 2.0 + Rails 5.1.4

### ISSUE THREAD

**Issue by girishv6991** [plataformatec/devise#4662]
I have been using Rails 5.0.0.1 with apartment 1.2.0. After upgrading rails(5.1.4) and apartment(2.0), I am having issues with persistent schema.

lib/tasks/db_enhancements
```
namespace :db do
  desc 'Also create shared_extensions Schema'
  task :extensions => :environment  do
    # Create Schema
    ActiveRecord::Base.connection.execute 'CREATE SCHEMA IF NOT EXISTS shared_extensions;'
    # Enable Hstore
    ActiveRecord::Base.connection.execute 'CREATE EXTENSION IF NOT EXISTS HSTORE SCHEMA shared_extensions;'
    # Enable UUID-OSSP
    ActiveRecord::Base.connection.execute 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA shared_extensions;'
    # Enable Postgis
    # Drop the postgis extension first
    ActiveRecord::Base.connection.execute 'DROP EXTENSION "postgis"';
    # Create postgis in shared_extensions
    ActiveRecord::Base.connection.execute 'CREATE EXTENSION IF NOT EXISTS "postgis" SCHEMA shared_extensions;'
  end
end

Rake::Task["db:create"].enhance do
  Rake::Task["db:extensions"].invoke
end

Rake::Task["db:test:purge"].enhance do
  Rake::Task["db:extensions"].invoke
end
```

config/initializers/apartment.rb
```
# Persistent schema
config.persistent_schemas = %w{ shared_extensions }
```
config/database.yml
```
default: &default
  adapter: postgis
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  schema_search_path: "public,shared_extensions"

development:
  <<: *default
  database: test_apartment_development

test:
  <<: *default
  database: test_apartment_test
```
Postgresql database enabled extensions
```
test_apartment_development=# \dx
                                         List of installed extensions
   Name    | Version |      Schema       |                             Description
-----------+---------+-------------------+---------------------------------------------------------------------
 hstore    | 1.3     | shared_extensions | data type for storing sets of (key, value) pairs
 plpgsql   | 1.0     | pg_catalog        | PL/pgSQL procedural language
 postgis   | 2.2.1   | shared_extensions | PostGIS geometry, geography, and raster spatial types and functions
 uuid-ossp | 1.0     | shared_extensions | generate universally unique identifiers (UUIDs)

test_apartment_test=# \dx
                                         List of installed extensions
   Name    | Version |      Schema       |                             Description
-----------+---------+-------------------+---------------------------------------------------------------------
 hstore    | 1.3     | shared_extensions | data type for storing sets of (key, value) pairs
 plpgsql   | 1.0     | pg_catalog        | PL/pgSQL procedural language
 postgis   | 2.2.1   | shared_extensions | PostGIS geometry, geography, and raster spatial types and functions
 uuid-ossp | 1.0     | shared_extensions | generate universally unique identifiers (UUIDs)
```
The following error is thrown when I try to migrate a table with `uuid` as `primiary key`
```
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function gen_random_uuid() does not exist
```
