### ISSUE TITLE
Unable to provide model-specific `already_authenticated` i18n key

### ISSUE THREAD

**Issue by artur-beljajev** [plataformatec/devise#5080]
```
en:
  devise:
    failure:
      already_authenticated: "You are already signed in."
      user:
        already_authenticated: ""
```

The latter with empty string is merely ignored. I wonder if it is a bug. If it's not, I find it useful to make it work in the same way as `sessions` key (https://github.com/plataformatec/devise#i18n).
